version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8 

  pre_build:
    commands:
      - echo "Pomijam logowanie do CodeArtifact - buduję z Maven Central..."

  build:
    commands:
      - echo "====== BEGINNING BUILD ======"
      - mvn clean install -DskipTests 

  post_build:
    commands:
      - echo "====== RUNNING TESTS ======"
      - chmod +x run-tests.sh
      - ./run-tests.sh
      - echo "====== PACKAGING ARTIFACT ======"
      - mvn package -DskipTests
      
artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
